#!/bin/bash
su cp
init Plasma-membrane
#it is a double layer of:
    lipid and .protein layer
cp -f [init lipid & protein bilayer]
 {are thin, tough, pliable and hydrophobic}
 cp -f/s {["therefore enabling the membrane to remain selectively 
    permiable to particles, of inorganic ions and molecules; with receptor
    proteins attatched to it"]}
fi
#it is the transport proteins on the bilayer surface that allow membrane transport
receptor proteins transport signals into the cell
membrane enzymes participate in reaction pathways
due to non-covalent bonding between lipid & protein layers the membrane remains flexible and change in shape:
cp -f {(/"bonding in the plasmamembrane"\/")}:
puts char:
#hydrophobic boning {includes: occures btwn the non-polar
                    #hydocarbon tail of phospolipid 
                    #causing an orientation of the phosphoipid head
                    #towards the aquous environment of ECF & ICF}
<!DOCTYPE html>
<head>
<!hydrogen bonding> 
 <html>
 <occures betwn:
 !polar headgroups of phospholipids/
 !phospholipids and other groups such as #protin & all polar molecule">

 cp ./ionic bonds {between charged particles}
 cp ./covalet bonds 
fi